[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zk_payment_request = "GDjvp1n9QMKKF1gtxFmCQLY3xFxu18ZLbmZBLaFN3kuq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"